apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: portfolio
spec:
  type: NodePort
  selector:
    app: portfolio
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30200
